import uuid
from datetime import date, datetime
from enum import Enum
from typing import TYPE_CHECKING

from sqlmodel import SQLModel, Field, Relationship, UniqueConstraint
from sqlalchemy import Column, DateTime, func

if TYPE_CHECKING:
    from models.users import User
    from models.itinerary import ItineraryItem
    from models.expenses import Expense
    from models.polls import Poll
    from models.availability import AvailabilitySlot
    from models.packing import PackingItem
    from models.notifications import NotificationLog


class EventRole(str, Enum):
    organizer = "organizer"
    guest = "guest"


class Event(SQLModel, table=True):
    __tablename__ = "events"

    # uuid, PK — generated by us when the event is created
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)

    # text (not null)
    title: str

    # text, nullable
    description: str | None = Field(default=None)

    # text, nullable
    location: str | None = Field(default=None)

    # date, nullable
    start_date: date | None = Field(default=None)

    # date, nullable
    end_date: date | None = Field(default=None)

    # text, nullable — Supabase Storage path
    cover_image_url: str | None = Field(default=None)

    # uuid, FK → users.id — the user who created the event
    created_by: str = Field(foreign_key="users.id", index=True)

    # timestamptz, default now() — set by Postgres
    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    )

    # timestamptz, default now()
    last_updated_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    )

    # last updated by, nullable
    last_updated_by: str | None = Field(default=None, foreign_key="users.id", index=True)

    # --- connections ---
    creator: "User" = Relationship(
        back_populates="events_created",
        sa_relationship_kwargs={"foreign_keys": "[Event.created_by]"},
    )
    members: list["EventMember"] = Relationship(
        back_populates="event", cascade_delete=True
    )
    invites: list["EventInvite"] = Relationship(
        back_populates="event", cascade_delete=True
    )
    itinerary_items: list["ItineraryItem"] = Relationship(
        back_populates="event", cascade_delete=True
    )
    expenses: list["Expense"] = Relationship(
        back_populates="event", cascade_delete=True
    )
    polls: list["Poll"] = Relationship(back_populates="event", cascade_delete=True)
    availability_slots: list["AvailabilitySlot"] = Relationship(
        back_populates="event", cascade_delete=True
    )
    packing_items: list["PackingItem"] = Relationship(
        back_populates="event", cascade_delete=True
    )
    notifications: list["NotificationLog"] = Relationship(
        back_populates="event", cascade_delete=True
    )


class EventMember(SQLModel, table=True):
    __tablename__ = "event_members"
    # a user can only be a member once per event
    __table_args__ = (UniqueConstraint("event_id", "user_id", name="uq_event_member"),)

    # uuid, PK
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)

    # uuid, FK → events.id
    event_id: uuid.UUID = Field(foreign_key="events.id", index=True, ondelete="CASCADE")

    # uuid, FK → users.id
    user_id: str = Field(foreign_key="users.id", index=True)

    # enum('organizer','guest')
    role: EventRole

    # timestamptz, default now()
    joined_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    )

    # --- connections ---
    event: Event = Relationship(back_populates="members")
    user: "User" = Relationship(back_populates="event_memberships")


class EventInvite(SQLModel, table=True):
    __tablename__ = "event_invites"

    # uuid, PK
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)

    # uuid, FK → events.id
    event_id: uuid.UUID = Field(foreign_key="events.id", index=True, ondelete="CASCADE")

    # text, unique — random invite token
    token: str = Field(unique=True, index=True)

    # uuid, FK → users.id — who generated the invite
    created_by: str = Field(foreign_key="users.id", index=True)

    # timestamptz, nullable
    expires_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True), nullable=True)
    )

    # timestamptz, default now()
    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    )

    # --- connections ---
    event: Event = Relationship(back_populates="invites")
    creator: "User" = Relationship(back_populates="event_invites_created")
