"""add last_updated_at and last_updated_by to itinerary_items and events

Revision ID: bf194cafcb06
Revises: 40a1ad678563
Create Date: 2026-09-20 13:30:41.475729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bf194cafcb06'
down_revision: Union[str, Sequence[str], None] = '40a1ad678563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_events_last_updated_by'), 'events', ['last_updated_by'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['last_updated_by'], ['id'])
    op.add_column('itinerary_items', sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('itinerary_items', sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_itinerary_items_last_updated_by'), 'itinerary_items', ['last_updated_by'], unique=False)
    op.create_foreign_key(None, 'itinerary_items', 'users', ['last_updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itinerary_items', type_='foreignkey')
    op.drop_index(op.f('ix_itinerary_items_last_updated_by'), table_name='itinerary_items')
    op.drop_column('itinerary_items', 'last_updated_by')
    op.drop_column('itinerary_items', 'last_updated_at')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_last_updated_by'), table_name='events')
    op.drop_column('events', 'last_updated_by')
    op.drop_column('events', 'last_updated_at')
    # ### end Alembic commands ###
